{+forward-override{forward-socks5 127.0.0.1:7070 .}}
.gameguardian.net
.kimsufi.com
.soyoustart.com
.ovh.net
.maying.co
.etherscan.io
.stackoverflow.com
.firmware.mobi
.gitlab.com
.helm.sh
.bintray.com
.kubernetes.io
.kubernetes.cn
.kubernetes.com
.githubusercontent.com
.github.com
.istanco.com
.kxcdn.com
.gitlab-static.net
.gitlab.com
.gitlab.io
.m-team.cc
.sleazyfork.org
.sourceforge.net
.viewdocs.io
.cloudflare.com
.vmware.com
.steampowered.com
.llnwd.net
.steamcommunity.com
.python.org
.wireguard.com
.zx2c4.com
.gitpod.io
.ws-us02.gitpod.io
.worldoftanks.com
.wgcdn.co
.tanksmod.com
.worldoftanks.eu
.wotbaza.com
.rackspace.com
.hkg.mirror.rackspace.com
.cloudgarage.jp
.amazon.com
.cloudfront.net
.docker.io
.docker.com
.github.com
.bintray.com
.pythonhosted.org
.parastorage.com
.digitalocean.com
.fastly.net
.mygiftcardsite.com
.1password.com
.vmware.com
.wireguard.com
.wordpress.org
.githubassets.com
.gitlab.com
.azureedge.net
.azure.net
.gitlab-static.net
.visualstudio.com
.sentry.io
.sentry-cdn.com
.ssl-images-amazon.com
.awsstatic.com
.cdn.optimizely.com
.sublimetext.com
.vo.msecnd.net
.packagecontrol.io
.daumcdn.net
.dnscrypt.info
.slack.com
.slack-edge.com
.istanco.com
.mzones.cc
.atrandys.com
.python.org
.pypi.org
.pythonhosted.org
.xposed.info
.maying.co
.etherscan.io
.packages.microsoft.com
.security.debian.org
.debian.org
.jsfiddle.net
.gravatar.com
.ledger.com
.bjango.com
.catpaws2012.com
.dwnews.com
.coolshell.cn
.kakao.com
.wikidevi.com
.daum.net
.go.microsoft.com
.hockeyapp.net
.firebaseio.com
.usage.readdle.com
.api.amplitude.com
.app.smartmailcloud.com
.synocommunity.com
.ncsoft.com
.plaync.com
.ncupdate.com
.tmdb.org
.themoviedb.org
.proxifier.com
.netflix.com
.nflximg.com
.nflximg.net
.nflxext.com
.nflxso.net
.nflxvideo.net
.fast.com
.v2ex.com
.mailgun.org
.acme.sh
.hpe.com
.wholetomato.com
.rubygems.org
.nrop19.com
.gamecdn.net
.jetbrains.com
.msdl.microsoft.com
.googleapis.com
.elitepvpers.com
.unknowncheats.me
.notepad-plus-plus.org
.fastlydns.net
.mxroute.com
.jetbrains.com
.account.jetbrains.com
.strawberryperl.com
.mir4global.com
.7-zip.org
.truenas.com 